{% set name = "python-keystoneclient" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc5e7719f4156425dec77d75c3a79918e3d0b519378a16d8d7efa8849e4c2a79

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python >=3.8
    - setuptools
  run:
    - debtcollector
    - keystoneauth1
    - oslo.config
    - oslo.i18n
    - oslo.serialization
    - oslo.utils
    - packaging
    - pbr
    - python >=3.8
    - requests
    - setuptools
    - six
    - stevedore

test:
  imports:
    - keystoneclient

about:
  home: https://github.com/openstack/python-keystoneclient
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Client Library for OpenStack Identity
  doc_url: https://docs.openstack.org/python-keystoneclient/latest/
  dev_url: https://opendev.org/openstack/python-keystoneclient

extra:
  recipe-maintainers:
    - tschoonj
